server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # gzip para servir liviano
    gzip on;
    gzip_types text/plain text/css application/javascript image/svg+xml;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # cache de imágenes/estáticos
    location ~* \.(png|jpg|jpeg|webp|svg|ico)$ {
        expires 7d;
        add_header Cache-Control "public";
    }
}
